// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAz_XtG7P0v9jkPl100_CbBPsyZ32aG34',
    appId: '1:988007689143:android:59d9087619e8fec28c9632',
    messagingSenderId: '988007689143',
    projectId: 'neat-tip',
    storageBucket: 'neat-tip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAouh_6hE6hic8QuU6WSJTjbPQ3KCSKktA',
    appId: '1:988007689143:ios:4682a6aa148acf568c9632',
    messagingSenderId: '988007689143',
    projectId: 'neat-tip',
    storageBucket: 'neat-tip.appspot.com',
    androidClientId: '988007689143-pfheh3dnjke5b0d92839gtmqtaea7huj.apps.googleusercontent.com',
    iosClientId: '988007689143-4ka6k84gbss20niapsv2ki82h629b2hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.neatTip',
  );
}
